### ISSUE TITLE
Reducir tamaño videos.

### ISSUE THREAD

**Issue by vigliensoni** [vigliensoni/mutek-hydra#1]
@whyohwhyoh, el video de explosiones pesa casi 94MB. Es pesado para web, en conexiones lentas pasará un rato hasta que descargue.

Creo que podríamos:

- cortar el video en las 6 partes que lo conforman y así quizás ocupar las partes que lo conforman en otros videos.
- reducir el tamaño de 1280 * 720 a 640 * 360 (o algo así)
- aplicar alguna compresión

Como ejemplo subí el video de las explosiones con esos cambios (solo el primero de los seis). De 94 MB pasamos a 1.5MB (https://github.com/vigliensoni/mutek-hydra/blob/master/fotos/videos/explosiones-slower-800.mp4) 

Para que lo tengas en tu repositorio local debes traerlo desde Github. Para eso debes selecctionar "Fetch Origin" en Github Desktop.

**Comment by whyohwhyoh** [comment]
Genial, recién leo esto.
Es cierto, de hecho el video era mucho más largo y pesado, y saque una version corta pero que claramente pudo ser mejor comprimida. Voy a tener en cuenta lo que me dices para las proximas pruebas.

**Comment by vigliensoni** [comment]
Los settings que ocupé para la última versión de los nueve videos es:

```bash
ffmpeg -i fall.mp4 -vf scale=100:-1 -filter:v "crop=640:360:60:60" -c:v libx264 -crf 25 -c:a copy fall-small.mp4
```
